# https://taskfile.dev

version: '3'

vars:
  APP_NAME: exp-page

tasks:
  default:
    cmds:
      - task: run
  build:
    cmds:
      - go build -o {{.APP_NAME}}{{exeExt}} .
    sources:
      - ./*.go
    generates:
      - ./{{.APP_NAME}}{{exeExt}}
  run:
    deps: [ build ]
    cmds:
      - ./{{.APP_NAME}}{{exeExt}} -file testdata/test01.docx -page 1
  clean:
    cmds:
      - cmd /c "rd /s /q .task"