# https://taskfile.dev

version: '3'

vars:
  APP_NAME: grep-docx

tasks:
  default:
    cmds:
      - task: run
  build:
    cmds:
      - go build -o {{.APP_NAME}}{{exeExt}} .
    sources:
      - ./*.go
    generates:
      - ./{{.APP_NAME}}{{exeExt}}
  run:
    deps: [ build ]
    cmds:
      - ./{{.APP_NAME}}{{exeExt}} -dir testdata -text "データベースファイルサイズ" -verbose
  clean:
    cmds:
      - cmd /c "rd /s /q .task"